name: CI

on:
  push:
    branches: [ "karsajobs-ui" ]

jobs:
  testing-and-building-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: lint-dockerfile
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x hadolint
          ./hadolint Dockerfile

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: hijazp
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build-app-karsajobs
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/hijazp/karsajobs-ui:latest

